### ISSUE TITLE
Question regarding responsive images

### ISSUE THREAD

**Issue by ewal** [cloudinary/pkg-cloudinary-core#10]
According to the Readme you can use `cl.image` to prepare an image with responsive functionality. Are you supposed to use the jQuery .responsive() method to fetch the image after it has been created and rendered or is there another way not using jQuery?

**Comment by taragano** [comment]
Hi @ewal,
Our core Javascript (without jQuery) also supports the `responsive` method.
Please see the following for example:
https://jsfiddle.net/tocker/jtfj3dc5/

**Comment by ewal** [comment]
Brilliant. Thank you!
