### ISSUE TITLE
Width: auto transform parameter do not work

### ISSUE THREAD

**Issue by moimael** [cloudinary/pkg-cloudinary-core#12]
HI,

I just migrated from cloudinary node version to this one, and the url generation seem broken in some case.

If I pass a transform object to cl.url with `width: 'auto'`, it's not present as w_auto in the url, while the other transform params are present.

Thanks.

**Comment by nadavofi** [comment]
Hi, can you try specifying a crop mode? You can use the default "scale" mode, e.g.:

    cl.url("sample.jpg", {width: "auto",crop: "scale"})

Let us know if it's working for you.

**Comment by nadavofi** [comment]
I'm closing this thread due to the time elapsed. Please feel free to follow up here or by opening another issue, or [contact Cloudinary's support](https://support.cloudinary.com/hc/en-us/requests/new)
