### ISSUE TITLE
Images returning 400 from cloudinary.url()

### ISSUE THREAD

**Issue by rpylipow** [cloudinary/pkg-cloudinary-core#17]
I'm receiving an error while trying to transform and fetch an image.

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

What's strange is that most of my images work as expected while others do not. I'm passing each image url through the same code.

```javascript
import * as cloudinary from 'cloudinary-core';
const cl = cloudinary.Cloudinary.new({ cloud_name: MY_CLOUD_NAME });

const image = cloudinary.url(SOME_IMAGE_URL, {
      width: 120,
      height: 120,
      crop: 'fit',
      quality: 'auto:best',
      fetch_format: 'auto',
      type: 'fetch',
});
```

Not working: http://res.cloudinary.com/structural/image/fetch/c_fit,f_auto,h_480,q_auto:best,w_480/http://blog.yourencore.com/hubfs/DeJongeWoodPR.png%3Ft%3D1492107211790

Working: http://res.cloudinary.com/structural/image/fetch/c_fit,f_auto,h_480,q_auto:best,w_480/http://blog.yourencore.com/hubfs/Pharmcast_Ep19_FeaturedImage.png%3Ft%3D1494510722775

It's likely that I'm making a dumb mistake, but the error message that I'm receiving isn't telling me much about what I'm doing wrong. 

Any ideas?

**Comment by mhoc** [comment]
https://support.cloudinary.com/hc/en-us/articles/202520592-Do-you-have-a-file-size-limit-

If you're on the free plan, Cloudinary has a file size limit of 10MB. It looks like your first image is around 12MB.

**Comment by rpylipow** [comment]
You're so smart. Thanks.

**Comment by eitanp461** [comment]
@rpylipow FYI, error details are returned by the `X-Cld-Error` header on the response
![image](https://cloud.githubusercontent.com/assets/3124855/26651097/4de1e86e-4654-11e7-9f07-2f3f2316dc17.png)
