### ISSUE TITLE
'cloudinary-core-shrinkwrap.min.js.map' Request Getting Caught within React Router 

### ISSUE THREAD

**Issue by wilbert-abreu** [cloudinary/pkg-cloudinary-core#18]
We have a request coming into our app server-side with a pathname of `/static/js/cloudinary-core-shrinkwrap.min.js.map` this request is getting caught within react router and matching on one of our routes. `/static/js` is the location of our js files. Based off of the `.map` file extension, it seems like this request is coming from within the package. Anyone have an idea why `cloudinary-core` is sending this request?

Thanks!

**Comment by eitanp461** [comment]
@wilbert-abreu Can you provide more details regarding your build tool setup?
How are bundling cloudinary-core?
Can you share the relevant config parts?

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
