### ISSUE TITLE
Obtaining cloudinary-core.js / cloudinary-core-shrinkwrap.js directly from cloudinary.com

### ISSUE THREAD

**Issue by ohadschn** [cloudinary/pkg-cloudinary-core#19]
The [installation instructions](https://github.com/cloudinary/pkg-cloudinary-core#installation) mention Bower and NPM, but seeing as Cloudinary is essentially a CDN it's a bit ironic that `cloudinary-core.js` itself [must be obtained from another CDN](https://cloudinary.com/blog/make_all_images_on_your_website_responsive_in_3_easy_steps#1_include_cloudinary_in_your_project) :)

**Comment by roeeba** [comment]
Hi @ohadschn, Cloudinary indeed utilizes a worldwide fast CDN in order to distribute its content. You can definitely upload the resource to your Cloudinary account and use its dedicated URL for this.

**Comment by ohadschn** [comment]
Yes, but then I would be eating my own quota...

I'm just saying that IMHO it would make sense to have something like: `https://cloudinary.com/ajax/libs/cloudinary-core/2.3.0/cloudinary-core-shrinkwrap.min.js`

**Comment by roeeba** [comment]
Thanks for the feedback! I've forwarded it to the relevant department.
