### ISSUE TITLE
Dependency on lodash throwing errors

### ISSUE THREAD

**Issue by ryan-ajmadison** [cloudinary/pkg-cloudinary-core#21]
My webpack is failing to compile and 'cloudinary-core' is throwing a bunch of errors regarding lodash:

ERROR in ./~/cloudinary-core/cloudinary-core.js Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in /node_modules/cloudinary-core @ ./~/cloudinary-core/cloudinary-core.js 34:11-320

I've tried installing different versions of lodash and this package, but no dice.

My package.json currently:
"lodash": "^3.10.1",
"react-cloudinary": "^0.2.1",

**Comment by idobarnoam** [comment]
Hey @ryan-ajmadison 

This issue also appears [here](https://github.com/cloudinary/cloudinary_npm/issues/183). 

In order to avoid confusion, we are closing this thread.
If you feel it should remain open, please re-open it.

Thanks
