### ISSUE TITLE
Client is heavyweight

### ISSUE THREAD

**Issue by anaibol** [cloudinary/pkg-cloudinary-core#5]
Hi, I noticed that adding the client to my application added 215kb to the minified build. Is that normal?
215kb it's a lot..
Could we split the client to have only the minimal code on the client?

 [175] ./~/cloudinary-core/cloudinary-core-shrinkwrap.js 215 kB {0} [built]

**Comment by tocker** [comment]
Hi @anaibol ,
The minified shrinkwrap version is only 70K.

**Comment by anaibol** [comment]
Hi, @tocker, 70kb is also a lot.
I finished using my own code.. In today's mobile and web js apps, 70kb is half of my code. Please consider not using external dependencies like lodash.
