### ISSUE TITLE
Source Map for cloudinary-core.js is referenced but not provided

### ISSUE THREAD

**Issue by justinappler** [cloudinary/pkg-cloudinary-core#6]
Line 3293 of cloudinary-core.js has the following reference to `cloudinary-core.js.map`: 

`//# sourceMappingURL=cloudinary-core.js.map`

However, that file is not included in the package and causes 'Missing sourcemap' errors.

**Comment by infinityfarm** [comment]
Also having this issue, also caused some very frustrating-to-debug router issues
