### ISSUE TITLE
Undefined variable rmargin 

### ISSUE THREAD

**Issue by kettuniko** [cloudinary/pkg-cloudinary-core#8]
https://github.com/cloudinary/pkg-cloudinary-core/blob/master/cloudinary-core.js#L147

**Comment by diegopamio** [comment]
I've got the same error, any clue? workaround? explanation?

Four months is like a lot for a bug like this one...

**Comment by nadavofi** [comment]
We're aware of the issue and the R&D team is working to fix it.
Meantime, here's how this issue can be resolved locally.

See: https://github.com/cloudinary/pkg-cloudinary-core/blob/efe4718781941a94940359ce567f3201d06bb8ae/cloudinary-core.js#L186

right above L186, please add the following assignment expression:

`rmargin = /^margin/;`

**Comment by taragano** [comment]
This issue is now fixed with the new version (2.1.3).
Can you please retry this and verify?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
